package com.diploma.proforientation.dto.ml;

import com.diploma.proforientation.dto.RecommendationDto;
import com.diploma.proforientation.model.TraitProfile;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

@Schema(description = "Final scoring result produced after evaluating a quiz attempt")
public record ScoringResult(
        @Schema(
                description = """
                        Calculated trait scores based on quiz answers.
                        Each entry maps a trait profile to its aggregated score.
                        """,
                example = """
                        {
                          "R": 12.5,
                          "I": 9.0,
                          "A": 7.5
                        }
                        """
        )
        Map<TraitProfile, BigDecimal> traitScores,
        @Schema(
                description = "List of profession recommendations generated by the ML scoring engine",
                example = """
                        [
                          {
                            "professionId": 42,
                            "score": 0.82,
                            "explanation": "Predicted as: Software Engineer"
                          }
                        ]
                        """
        )
        List<RecommendationDto> recommendations
) {}