INSERT INTO profession_categories (code, name)
VALUES
  ('sap',                 'SAP-специалисты'),
  ('it',                  'IT / Программирование / Разработка'),
  ('engineering',         'Инженерные профессии'),
  ('healthcare_medical',  'Медицина / Здравоохранение'),
  ('general',            'Общие направления / прочее');

DO $$
    DECLARE
        names_en  text[] := ARRAY[
            'Accounting','Actuarial Science','Administration / Office Management',
            'Advertising / Marketing','Agricultural Economics','Agriculture / Agribusiness',
            'Animal Science / Veterinary','Animation / Game Design','Anthropology',
            'Archaeology','Art / Fine Arts','Artificial Intelligence / Machine Learning',
            'Artificial Intelligence / Robotics Engineering','Aviation',
            'Automotive / Mechanical Technology','Banking / Finance',
            'Bioengineering / Biomedical Engineering','Biochemistry',
            'Biology / Life Sciences','Biomedical Science','Biophysics',
            'Biotechnology','Business Administration / Management',
            'Cartography / Spatial Analysis','Chemical Engineering','Chemistry',
            'Child Development / Early Childhood Education','Civil Engineering',
            'Cognitive Science / Neuroscience','Communication / Media Studies',
            'Community Development / Social Services','Computer Engineering',
            'Computer Science / Information Technology','Construction / Building Management',
            'Counseling / Therapy','Creative Writing','Criminal Justice / Law Enforcement',
            'Criminal Psychology','Cultural Studies / Heritage',
            'Cybersecurity / Information Security','Data Science / Statistics',
            'Dental / Oral Health','Design','Dietetics / Nutrition',
            'Digital Marketing / E-commerce','Drama / Theatre / Performing Arts',
            'Economics','Education / Teaching','Electrical Engineering',
            'Electronic Engineering','Emergency Management / Public Safety',
            'Energy / Petroleum Engineering','English / Literature / Linguistics',
            'Environmental Science / Sustainability','Epidemiology','Scriptwriting',
            'Fashion / Textile Design','Film / TV / Media Production',
            'Finance / Investment','Food Science / Food Technology',
            'Forensic Science / Criminalistics','Genetics',
            'Gender Studies / Feminist Studies','Geography / GIS',
            'Geology / Earth Science','Graphic Design','Health Administration / Health Management',
            'Healthcare / Medicine','History / Archaeology',
            'Hospitality Management / Tourism','Human Resources / Organizational Development',
            'Humanities / Liberal Arts','Industrial / Organizational Psychology',
            'Industrial Design','Industrial Engineering / Manufacturing',
            'Information Systems / Data Management','Interior Design',
            'International Relations / Political Science','Journalism',
            'Kinesiology / Exercise Science','Law / Legal Studies',
            'Library and Information Science','Linguistics',
            'Logistics / Supply Chain Management','Management Information Systems',
            'Marine / Oceanography','Materials Science / Nanotechnology',
            'Mathematics / Applied Mathematics','Mechanical Engineering',
            'Media and Communication','Medical Laboratory Science',
            'Military Science / Defense Studies','Ministry / Religious Studies / Theology',
            'Molecular Biology','Music / Music Technology',
            'Nanotechnology / Materials Science','Nursing','Occupational Therapy',
            'Operations Management','Optometry / Vision Science',
            'Paralegal / Legal Assistance','Pharmacy / Pharmacology',
            'Philosophy / Ethics','Physical Therapy / Rehabilitation',
            'Physics / Astronomy','Political Science / Governance',
            'Product Design','Psychology','Public Administration / Public Policy',
            'Public Health','Publishing','Real Estate / Property Management',
            'Robotics / Automation Engineering','Social Work / Human Services',
            'Sociology / Social Sciences','Software Engineering / Programming',
            'Speech Language Pathology','Sports Management',
            'Systems Engineering / Technology Management','Urban Planning',
            'Veterinary Medicine / Animal Care','Visual Communication',
            'Culinary',
            'Clinical Psychology',
            'Microbiology',
            'Translation / Interpretation Studies',
            'Aerospace Engineering',
            'Counseling Psychology / Therapy'
            ];
        names_ru  text[] := ARRAY[
            'Бухгалтер','Актуарий','Офис-менеджер',
            'Маркетолог','Аграрный экономист','Агроном',
            'Ветеринар','Гейм-дизайнер','Антрополог',
            'Археолог','Художник','ML-инженер',
            'Инженер по робототехнике','Специалист по авиации',
            'Автомеханик','Финансист',
            'Биомедицинский инженер','Биохимик',
            'Биолог','Биомедицинский исследователь','Биофизик',
            'Биотехнолог','Бизнес-менеджер',
            'Картограф','Инженер-химик','Химик',
            'Педагог раннего развития','Инженер-строитель',
            'Нейроучёный','Специалист по коммуникациям',
            'Социальный координатор','Инженер-вычислительщик',
            'IT-специалист','Руководитель строительства',
            'Психолог-консультант','Писатель',
            'Сотрудник правоохранительных органов',
            'Криминальный психолог','Специалист по культурному наследию',
            'Специалист по кибербезопасности','Data Scientist',
            'Стоматолог','Дизайнер','Диетолог',
            'Интернет-маркетолог','Актёр',
            'Экономист','Преподаватель','Инженер-электрик',
            'Инженер-электроник','Специалист по ЧС',
            'Инженер-нефтяник','Филолог-англист',
            'Эколог','Эпидемиолог','Сценарист',
            'Дизайнер одежды','Видеооператор',
            'Инвестиционный аналитик','Технолог пищевого производства',
            'Судебный эксперт','Генетик',
            'Исследователь гендерных проблем','Географ',
            'Геолог','Графический дизайнер','Менеджер здравоохранения',
            'Врач','Историк',
            'Менеджер по туризму','HR-специалист',
            'Гуманитарий','Организационный психолог',
            'Промышленный дизайнер','Инженер по производству',
            'Системный аналитик','Дизайнер интерьеров',
            'Политолог-международник','Журналист',
            'Реабилитолог','Юрист',
            'Библиотекарь','Лингвист',
            'Логист','MIS-аналитик',
            'Океанолог','Инженер по материалам',
            'Математик','Инженер-механик',
            'Медиа-специалист','Лаборант-диагност',
            'Военный аналитик','Теолог',
            'Молекулярный биолог','Звукорежиссёр',
            'Нанотехнолог','Медсестра',
            'Эрготерапевт','Операционный менеджер',
            'Оптометрист','Помощник юриста',
            'Фармацевт','Философ',
            'Физиотерапевт','Физик',
            'Политолог','Продуктовый дизайнер',
            'Психолог','Госслужащий',
            'Специалист по общественному здоровью',
            'Издательский менеджер','Риелтор',
            'Инженер по автоматизации','Социальный работник',
            'Социолог','Программист',
            'Логопед','Спортивный менеджер',
            'Системный инженер','Градостроитель',
            'Ветеринарный врач','Специалист по визуальным коммуникациям',
            'Кулинар',
            'Клинический психолог',
            'Микробиолог',
            'Переводчик / Специалист по интерпретации',
            'Аэрокосмический инженер',
            'Психолог-консультант'
            ];
        desc_en   text[] := ARRAY[
            'Accounting: managing financial records, auditing, and preparing financial reports.',
            'Actuarial Science: analyzing financial risk using mathematics, statistics, and modeling.',
            'Office administration and management of organizational processes.',
            'Creating and promoting products through communication and market strategy.',
            'Applying economic principles to agriculture and resource management.',
            'Working in agricultural production and farm business operations.',
            'Working with animals in research, care, breeding, or veterinary medicine.',
            'Designing animations, game mechanics, and interactive digital experiences.',
            'Studying human cultures, origins, and social evolution.',
            'Studying human history through excavation and artifact analysis.',
            'Creative visual or performing arts: painting, sculpture, photography.',
            'Developing AI systems, models, and machine learning applications.',
            'Building intelligent robotics systems integrating AI algorithms.',
            'Operating aircraft, aviation systems, and flight operations.',
            'Maintaining and repairing mechanical and automotive systems.',
            'Managing banking operations, finances, and investments.',
            'Engineering solutions for healthcare and biological systems.',
            'Studying chemical processes in living organisms.',
            'Researching living organisms and life systems.',
            'Biomedical research with medical and biological applications.',
            'Studying physical principles of biological systems.',
            'Using biological processes for industrial and medical innovation.',
            'Managing business operations, strategy, and organizational functions.',
            'Mapping and analyzing spatial data and environments.',
            'Applying chemistry to industrial production and materials.',
            'Studying matter, reactions, and chemical processes.',
            'Supporting early childhood learning and development.',
            'Designing and building infrastructure and public works.',
            'Studying cognition, the brain, and human intelligence.',
            'Analyzing media systems, communication, and public messaging.',
            'Supporting social programs and community development.',
            'Designing computer hardware and embedded systems.',
            'Programming, software engineering, and systems architecture.',
            'Managing construction projects and building operations.',
            'Providing psychological therapy and client counseling.',
            'Writing novels, scripts, or creative literary works.',
            'Enforcing law, ensuring public safety, and criminal investigation.',
            'Studying behavior of criminals and psychological profiles.',
            'Preserving cultural memory, artifacts, and traditions.',
            'Protecting systems from cyber threats and vulnerabilities.',
            'Analyzing data to extract insights and build predictive models.',
            'Providing dental care and oral disease treatment.',
            'Designing physical or digital products and user experiences.',
            'Developing nutritional plans and supporting healthy lifestyles.',
            'Managing online marketing, branding, and digital commerce.',
            'Producing theater, film, and performing arts.',
            'Studying economic systems and market behavior.',
            'Teaching and directing educational processes.',
            'Designing, analyzing, and maintaining electrical systems.',
            'Engineering advanced electronic systems and devices.',
            'Managing emergencies and protecting public safety.',
            'Engineering energy systems and petroleum extraction.',
            'Studying language, literature, and communication.',
            'Protecting ecosystems and promoting sustainability.',
            'Studying disease patterns in populations.',
            'Writing film scripts, shows, and media content.',
            'Designing clothing, textiles, and fashion products.',
            'Producing films, TV shows, and multimedia content.',
            'Managing investments, markets, and financial instruments.',
            'Developing food products and analyzing food processes.',
            'Investigating crimes using scientific methods.',
            'Studying heredity, genes, and genetic variation.',
            'Analyzing gender, society, and cultural roles.',
            'Studying Earth’s surface, climate, and environments.',
            'Studying Earth processes, rocks, and geological systems.',
            'Designing visual content for print and digital media.',
            'Managing healthcare organizations and systems.',
            'Providing medical care and diagnostics.',
            'Studying human history and cultural evolution.',
            'Managing tourism, hotels, and travel services.',
            'Managing HR, talent, and organizational culture.',
            'Studying humanities, languages, and human society.',
            'Studying workplace behavior and organizational psychology.',
            'Designing products and improving manufacturing processes.',
            'Engineering industrial systems and production flows.',
            'Managing company information systems and data.',
            'Designing indoor spaces and architectural interiors.',
            'Analyzing international politics and global relations.',
            'Writing, reporting, and producing news.',
            'Studying human movement and physical performance.',
            'Studying laws, legal systems, and court processes.',
            'Managing information resources and digital libraries.',
            'Studying language structure and linguistic theory.',
            'Managing logistics chains and supply operations.',
            'Managing IT systems for organizations.',
            'Studying oceans, marine life, and underwater systems.',
            'Creating advanced materials and nanotechnologies.',
            'Studying mathematics and applying advanced modeling.',
            'Engineering machines, devices, and mechanical systems.',
            'Analyzing media, journalism, and public communication.',
            'Conducting medical laboratory tests and diagnostics.',
            'Studying military strategy and defense systems.',
            'Studying religion, theology, and spiritual traditions.',
            'Studying molecular structures and biological processes.',
            'Creating music, audio engineering, and sound production.',
            'Engineering nanoscale materials and technologies.',
            'Providing nursing care and patient support.',
            'Helping patients restore function and adapt physically.',
            'Managing business operations and workflows.',
            'Testing and maintaining vision and eye health.',
            'Supporting attorneys and preparing legal documents.',
            'Studying and dispensing medications.',
            'Studying ethics, logic, and philosophical inquiry.',
            'Helping patients recover physical function.',
            'Studying matter, energy, and the universe.',
            'Studying political systems and governance.',
            'Designing consumer and industrial products.',
            'Studying human behavior and mental processes.',
            'Managing public programs and government policy.',
            'Promoting health and preventing disease.',
            'Managing publishing processes and publications.',
            'Managing property, real estate, and development.',
            'Engineering automation systems and robotics.',
            'Supporting social welfare and human services.',
            'Studying society, culture, and social systems.',
            'Programming and developing software systems.',
            'Diagnosing and treating communication disorders.',
            'Managing sports teams and athletic programs.',
            'Engineering complex systems and integrations.',
            'Designing urban areas and city infrastructure.',
            'Providing veterinary care and animal treatment.',
            'Designing visual communications and branding.',
            'Preparing food and developing culinary products.',
            'Studying mental disorders in clinical settings.',
            'Studying microorganisms and their environments.',
            'Translating and interpreting languages.',
            'Engineering aircraft and aerospace systems.',
            'Providing psychological counseling and therapy.'
            ];
        desc_ru   text[] := ARRAY[
            'Бухгалтерский учёт, ведение финансовой отчётности и аудит.',
            'Оценка финансовых рисков с помощью математики и статистических моделей.',
            'Администрирование и организация офисных процессов.',
            'Создание и продвижение продуктов с помощью маркетинговых стратегий.',
            'Применение экономических принципов в аграрной сфере.',
            'Управление сельским хозяйством и агропроизводством.',
            'Работа с животными в ветеринарии, уходе и исследовательских проектах.',
            'Создание анимации, игровых механик и цифровых визуальных материалов.',
            'Изучение культур, происхождения и социальной эволюции человека.',
            'Изучение истории через археологические раскопки и анализ артефактов.',
            'Творческая деятельность в области изобразительного и прикладного искусства.',
            'Разработка систем искусственного интеллекта и алгоритмов машинного обучения.',
            'Создание интеллектуальных робототехнических систем.',
            'Эксплуатация воздушного транспорта и авиационных технологий.',
            'Ремонт и обслуживание механических и автомобильных систем.',
            'Управление финансами, банковскими продуктами и инвестициями.',
            'Разработка инженерных решений для медицины и биологии.',
            'Изучение химических процессов, происходящих в живых организмах.',
            'Исследование живых организмов и биологических систем.',
            'Биомедицинские исследования и разработки.',
            'Изучение физических процессов в биологических системах.',
            'Использование биологических процессов для промышленности и медицины.',
            'Управление бизнес-процессами, стратегией и организацией.',
            'Создание карт и анализ пространственных данных.',
            'Применение химии в промышленности и материаловедении.',
            'Изучение вещества, реакций и химических процессов.',
            'Развитие и обучение детей раннего возраста.',
            'Проектирование и строительство инфраструктурных объектов.',
            'Изучение когнитивных процессов, мозга и интеллекта.',
            'Анализ медиа, коммуникации и публичной информации.',
            'Работа с социальными программами и развитием сообществ.',
            'Разработка аппаратного обеспечения и встроенных систем.',
            'Программирование, разработка ПО и архитектура систем.',
            'Управление строительными проектами и объектами.',
            'Психологическое консультирование и терапия.',
            'Создание художественных текстов и литературных произведений.',
            'Обеспечение общественной безопасности и расследование преступлений.',
            'Изучение поведения преступников и криминальной психологии.',
            'Сохранение культурного наследия и артефактов.',
            'Защита информационных систем от киберугроз.',
            'Анализ данных и построение предиктивных моделей.',
            'Предоставление стоматологической помощи.',
            'Проектирование физических и цифровых продуктов.',
            'Разработка программ питания и поддержание здорового образа жизни.',
            'Управление онлайн-маркетингом и электронной коммерцией.',
            'Создание театральных и кино постановок.',
            'Изучение экономических систем и рыночных процессов.',
            'Обучение и педагогическая деятельность.',
            'Разработка и обслуживание электрических систем.',
            'Проектирование и разработка электронных устройств.',
            'Обеспечение безопасности и реакция на чрезвычайные ситуации.',
            'Разработка энергетических систем и добыча нефти.',
            'Изучение языка, литературы и коммуникации.',
            'Охрана окружающей среды и устойчивое развитие.',
            'Изучение распространения заболеваний в популяциях.',
            'Создание сценариев для фильмов и других медиа.',
            'Разработка одежды, текстиля и модных продуктов.',
            'Создание фильмов, телепрограмм и мультимедийного контента.',
            'Управление инвестициями и финансовыми инструментами.',
            'Разработка пищевых продуктов и анализ пищевых процессов.',
            'Расследование преступлений с использованием научных методов.',
            'Изучение генов, наследственности и генетической вариативности.',
            'Исследование вопросов гендера, общества и культуры.',
            'Изучение земной поверхности, климата и географии.',
            'Исследование геологических процессов и структуры Земли.',
            'Создание визуальных материалов для цифровых и печатных носителей.',
            'Управление медицинскими организациями и системами.',
            'Диагностика и лечение заболеваний.',
            'Изучение истории и культурного наследия.',
            'Управление туризмом, гостиницами и туристическими услугами.',
            'Управление персоналом и организационным развитием.',
            'Изучение гуманитарных наук и человеческой культуры.',
            'Изучение поведения людей в рабочих организациях.',
            'Проектирование и создание продуктов.',
            'Инженерия и оптимизация производственных процессов.',
            'Управление корпоративными информационными системами.',
            'Проектирование интерьеров и архитектурных пространств.',
            'Изучение международных отношений и политики.',
            'Сбор, анализ и распространение новостной информации.',
            'Изучение движений человека и спортивной науки.',
            'Изучение права, юридических процессов и судебной системы.',
            'Управление информационными ресурсами и библиотеками.',
            'Изучение структуры языка и лингвистических закономерностей.',
            'Управление логистикой, цепочками поставок и складированием.',
            'Управление ИТ системами компаний.',
            'Изучение океанов, морской жизни и подводных процессов.',
            'Создание наноматериалов и высокотехнологичных покрытий.',
            'Изучение математики и применение моделей.',
            'Проектирование машин, механизмов и механических систем.',
            'Анализ журналистики, медиа и общественных коммуникаций.',
            'Проведение лабораторных медико-биологических исследований.',
            'Изучение военной стратегии и оборонных систем.',
            'Изучение религии, теологии и духовных традиций.',
            'Исследование молекулярных структур и процессов.',
            'Создание музыки, аудио и звукорежиссура.',
            'Разработка нанотехнологий и материалов на наноуровне.',
            'Предоставление сестринской помощи пациентам.',
            'Помощь людям в восстановлении двигательных функций.',
            'Управление бизнес-процессами и организацией.',
            'Диагностика и коррекция зрения.',
            'Юридическая помощь и подготовка документов.',
            'Изучение лекарств и их применения.',
            'Изучение философии, логики и этики.',
            'Помощь в восстановлении физического здоровья.',
            'Изучение физики, космоса и природных явлений.',
            'Изучение политических систем и государственного управления.',
            'Проектирование потребительских и промышленных продуктов.',
            'Изучение психики и поведения человека.',
            'Управление государственными программами и политикой.',
            'Охрана здоровья населения и профилактика болезней.',
            'Управление процессами издательской деятельности.',
            'Управление недвижимостью и развитием территорий.',
            'Разработка робототехнических систем и автоматизации.',
            'Работа в социальных службах и помощь населению.',
            'Изучение общества, культуры и социальных структур.',
            'Разработка ПО и программных решений.',
            'Диагностика нарушений речи и коммуникации.',
            'Управление спортивными организациями и мероприятиями.',
            'Инженерия сложных систем и интеграций.',
            'Проектирование городской среды и инфраструктуры.',
            'Лечение и уход за животными.',
            'Создание визуальных коммуникаций и брендинга.',
            'Кулинарное мастерство и создание блюд.',
            'Изучение психических расстройств в клинической среде.',
            'Исследование микроорганизмов и микробных процессов.',
            'Письменный и устный перевод.',
            'Проектирование авиационных и космических систем.',
            'Психологическое консультирование и терапия.'
            ];
        idx integer;
        v_code text;
    BEGIN
        FOR idx IN 1..array_length(names_en,1)
            LOOP
                -- Generate slug code
                v_code := regexp_replace(lower(names_en[idx]), '[^a-z0-9]+', '_', 'g');
                v_code := regexp_replace(v_code, '_+', '_', 'g');
                v_code := regexp_replace(v_code, '^_+|_+$', '', 'g');

                -- 1) Insert profession (only if not exists)
                INSERT INTO professions(code, title_default, description, category_id, ml_class_code)
                VALUES (
                           v_code,
                           names_en[idx],
                           desc_en[idx],  -- en description directly into table
                           (SELECT id FROM profession_categories WHERE code = 'general'),
                           names_en[idx]  -- ML class code
                       )
                ON CONFLICT (code) DO NOTHING;

                -- 2) Add Russian title translation
                INSERT INTO translations(entity_type, entity_id, locale, field, text)
                SELECT 'profession', p.id, 'ru', 'title', names_ru[idx]
                FROM professions p WHERE p.code = v_code
                ON CONFLICT DO NOTHING;

                -- 3) Add Russian description translation
                INSERT INTO translations(entity_type, entity_id, locale, field, text)
                SELECT 'profession', p.id, 'ru', 'description', desc_ru[idx]
                FROM professions p WHERE p.code = v_code
                ON CONFLICT DO NOTHING;

            END LOOP;
    END $$;

INSERT INTO professions (code, title_default, description, category_id, ml_class_code)
VALUES
  ('sap_consultant',
   'SAP Consultant',
   'Специалист по внедрению и настройке решений SAP.',
   (SELECT id FROM profession_categories WHERE code = 'sap'),
   NULL),

  ('sap_ux_designer',
   'SAP UX Designer',
   'Дизайнер пользовательских интерфейсов SAP Fiori / UI5.',
   (SELECT id FROM profession_categories WHERE code = 'sap'),
   NULL),

  ('sap_project_manager',
   'SAP Project Manager',
   'Менеджер проектов по внедрению SAP.',
   (SELECT id FROM profession_categories WHERE code = 'sap'),
   NULL),

  ('sap_developer',
   'SAP Developer',
   'Разработчик SAP (ABAP / SAPUI5 / BTP).',
   (SELECT id FROM profession_categories WHERE code = 'sap'),
   NULL);
