package com.diploma.proforientation.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;

@Schema(description = "Career recommendation generated by the scoring engine")
public record RecommendationDto(
        @Schema(
                description = "Identifier of the recommended profession",
                example = "42"
        )
        Integer professionId,
        @Schema(
                description = "Identifier of the recommended profession",
                example = "42"
        )
        BigDecimal score,
        @Schema(
                description = "Human-readable explanation of why this profession was recommended",
                example = "Predicted as: Software Engineer"
        )
        String explanation
) {}